###
POST http://localhost:8080/api/example06/login
Content-Type: application/json

{
  "userName": "BO",
  "password": "123456"
}
###
GET http://localhost:8080/api/example06/admin/welcome
###
GET http://localhost:8080/api/example06/admin/welcome
token:89c6cd18ae9d0f5ddb00398a9d04148a0bce6604bd66088faa81d267f232258e04541d9d79b465944db6c4e0b49980cc
###