###
POST http://localhost:8080/api/example03/users
Content-Type: application/json

{
  "name": "T",
  "age": 17,
  "email": "abc"
}
###
GET http://localhost:8080/api/example03/users/aaa/file
###
POST http://localhost:8080/api/example03/users
Content-Type: application/json

{
  "name": 123,
  "age": "abc",
  "email": 123
}
### 请求地址参数校验
GET http://localhost:8080/api/example03/users/s

###