###
POST http://localhost:8080/api/experiment08/register
Content-Type: application/json

{
  "userName": "BO",
  "password": "123456"
}
###
POST http://localhost:8080/api/experiment08/login
Content-Type: application/json

{
  "userName": "BO",
  "password": "123456"
}
###
POST http://localhost:8080/api/experiment08/login
Content-Type: application/json

{
  "userName": "XX",
  "password": "123456"
}
###
GET http://localhost:8080/api/experiment08/index
Token: cb4cba6352013a4366b844541cb9c7d9e5be3d901f71f340ce1ede470195c019e0042c1bf23ccb9633f49d7f80bddce7
###