###
GET http://localhost:8080/api/experiment07/users
###
GET http://localhost:8080/api/experiment07/users/12
###
POST http://localhost:8080/api/experiment07/users1
Content-Type: application/json

{
  "id": "1231",
  "password": "msg"
}
###